### ISSUE TITLE
Improve README to explain what this is better

### ISSUE THREAD

**Issue by sirinoks** [DevelopingSpace/docker.cdot.systems#11]
Having read the current README, I could not figure out exactly what this is. This is the idea I got:
> So far as I understand, this has something to do with authentication into (already running?deployed?) docker containers of our microservices.. Is this used in telescope, satellite, or all? 

There needs to be a better explanation on what it does, where it's used, who it's used by etc. If someone explains it to me, I can update the doc myself once I know.

**Comment by humphd** [comment]
A Docker Registry is a database of Docker Images that you can `push` or `pull`.  We host our own for Telescope, since we have so many different containers/images to deal with, and there are limits on Docker Hub and GitHub that we'll exceed.  This is (currently) only used for Telescope.

**Comment by sirinoks** [comment]
Added a "What is this" section to README. I'd say that's good enough for now.
