### ISSUE TITLE
Set up Authorization tokens for CI

### ISSUE THREAD

**Issue by TDDR** [DevelopingSpace/docker.cdot.systems#3]
Before we can start officially using our registry, we must set up authorization tokens for our CI pipeline. 

![image](https://user-images.githubusercontent.com/59970326/157486100-0b97f264-b1dd-4af6-a38f-007525c3b762.png)

https://github.com/cesanta/docker_auth/blob/main/examples/reference.yml#L122-L163

**Comment by humphd** [comment]
The fastest path to having something usable soon might be to do static users defined in the `config` file:

https://github.com/cesanta/docker_auth/blob/main/examples/simple.yml

We couldn't put that in git, but we could do it on the server.  This might let us get this into production within the week vs waiting on a perfect solution.  Thoughts?

cc @manekenpix, @Kevan-Y for thoughts.

**Comment by manekenpix** [comment]
@humphd :+1:

**Comment by Kevan-Y** [comment]
@humphd That would be a simple way, and maybe the best way for now for CI pipeline.
I was also searching if we setup auth with GitHub https://github.com/cesanta/docker_auth/blob/main/examples/reference.yml#L122-L163 how we gonna do the CI with that. 
```
# GitHub authentication.
# ==! NB: DO NOT ENTER YOUR GITHUB PASSWORD AT "docker login". IT WILL NOT WORK.
# Instead, Auth server maintains a database of GitHub authentication tokens.
# Go to the server's port as HTTPS with your browser and follow the "Login with GitHub account" link.
# Once signed in, you will get a throw-away password which you can use for Docker login.
```
Seems like user have to go to browser to login, that what I understand, not sure if I misunderstand that.

**Comment by humphd** [comment]
I propose that we modify our `docker-compose` file to add a [volume for the config](https://github.com/Seneca-CDOT/docker.cdot.systems/blob/main/docker-compose.yaml#L28-L29), but that we don't provide the actual config in git.  We'll manually create it in the server and include the right usernames and passwords.
