### ISSUE TITLE
Support pull-through proxying of Docker Hub

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/docker.cdot.systems#9]
We'd like to be able to cache things like Redis, Elasticsearch, etc from Docker Hub in our registry, so we can pull from it without network latency, etc.

To do this, we have to update https://github.com/Seneca-CDOT/docker.cdot.systems/blob/main/config/registry/config.yml and add:

```yaml
proxy:
  remoteurl: https://registry-1.docker.io
```

Then we should be able to use `docker pull docker.cdot.systems/redis` or whatever.

**Comment by humphd** [comment]
Filed https://github.com/Seneca-CDOT/telescope/issues/3222 to use this once it gets done.

**Comment by humphd** [comment]
See docs in https://docs.docker.com/registry/recipes/mirror/

**Comment by TueeNguyen** [comment]
Is our registry private? If not then we don't have to care about username and password

**Comment by humphd** [comment]
The username/password would be for proxying a private registry, which we don't need to do.  In this case, you're right, I don't think we need credentials.

**Comment by TueeNguyen** [comment]
Been reading this up, I can probably work on this and the other issue too

I have a question: what kind of `remoteurl` should we use for `proxy`? Could it be `localhost:5001` (and we would open a port for this mirror registry).

**Comment by humphd** [comment]
You would literally use `https://registry-1.docker.io/`, the Docker Hub registry.  We're pulling from them, caching in our registry, and publishing that via our main URL.
